name: Run Prettier

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Prettify code
      uses: creyD/prettier_action@v3.3
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write --config .prettierrc.json ./src/**/*.{ts,tsx}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
